name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  IMAGE_NAME: gttfe-a
  REACT_APP_AUTH_REDIRECT: /login
  REACT_APP_BACKEND_URL: ''
  PUBLIC_URL: "/admin"
  REACT_APP_COMMIT_HASH: ${{ github.sha }}

jobs:

  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.x]

    permissions:
      packages: write
      contents: read

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - name: Build app
      run: npm ci && npm run build
    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
    - name: Log in to registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $ --password-stdin
    - name: Build and push the Docker image
      run: |
          IMAGE_ID=ghcr.io/${{ github.repository_owner }}/$IMAGE_NAME
          IMAGE_ID=$(echo $IMAGE_ID | tr '[A-Z]' '[a-z]')
          VERSION=$(echo "${{ github.ref }}" | sed -e 's,.*/\(.*\),\1,')
          [[ "${{ github.ref }}" == "refs/tags/"* ]] && VERSION=$(echo $VERSION | sed -e 's/^v//')
          echo IMAGE_ID=$IMAGE_ID
          echo VERSION=$VERSION
          docker buildx build . --platform linux/amd64,linux/arm64 --file Dockerfile --tag $IMAGE_ID:latest --tag $IMAGE_ID:stable --tag $IMAGE_ID:$VERSION --label "runnumber=${GITHUB_RUN_ID}" --push
